services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: Vlad
      POSTGRES_PASSWORD: postgres2025
      POSTGRES_DB: Main
    volumes:
      - database_data:/var/lib/postgresql/data

  basketRedis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "basketRedis-data:/data"

volumes:
  database_data:
  basketRedis-data:
